
export interface Asset {
  id: number,
  assetNum: string,
  assetType: string,
  assetModel: string,
  specs: string,
  bundleNum: number,
  serialNum: string,
  pchOrder: string,
  salesInv: string,
  delivRct: string,
  supplier: string,
  acqDate: Date,
  warrantyDur: number,
  warrEndDate: Date,
  currency: string,
  unitCost: number,
  pezaZone: string,
  mktCircle: string,
  class: string,
  remarks: string,
  status: string,
  statEffDate: Date,
  location: string,
  locRemarks: string,
  locEffDate: Date,
  invRemarks: string,
  recInvDate: Date,
  employeeID: number,
}

