
export interface Asset {
  id: number,
  assetNum: string,
  assetType: string,
  assetModel: string,
  specs: string,
  bundleNum: number,
  serialNum: string,
  pchOrder: string,
  salesInv: string,
  delivRct: string,
  supplier: string,
  acqDate: Date,
  warrantyDur: number,
  warrEndDate: Date | null,
  currency: string,
  unitCost: number,
  pezaZone: string,
  mktCircle: string,
  class: string,
  remarks: string | null,
  status: string,
  statEffDate: Date,
  location: string,
  locRemarks?: string | null,
  locEffDate: Date,
  invRemarks: string | null,
  recInvDate: Date,
  employeeID: number | null,
}

export const titles = {
  assetNum: 'Asset No.',
  assetType: 'Asset Type',
  assetModel: 'Asset Model',
  specs: 'Specs',
  bundleNum: 'Bundle No.',
  serialNum: 'Serial No.',
  pchOrder: 'Purchase Order',
  salesInv: 'Sales Inv.',
  delivRct: 'Delivery Receipt',
  supplier: 'Supplier',
  acqDate: 'Acq. Date',
  warrantyDur: 'Warranty',
  warrEndDate: 'Warr. End',
  currency: 'Currency',
  unitCost: 'Unit Cost',
  pezaZone: 'PEZA Zone',
  mktCircle: 'Market Circle',
  class: 'Classification',
  remarks: 'Remarks',
  status: 'Status',
  statEffDate: 'Status Eff.',
  location: 'Location',
  locRemarks: 'Location Remarks',
  locEffDate: 'Location Eff. Date',
  invRemarks: 'Inv. Remarks',
  recInvDate: 'Rec. Inv.',
  employeeID: 'User',
}

